export enum Configuration {
  POSTGRE_HOST = 'POSTGRE_HOST',
  POSTGRE_PORT = 'POSTGRE_PORT',
  POSTGRE_USER = 'POSTGRE_USER',
  POSTGRE_PASSWORD = 'POSTGRE_PASSWORD',
  POSTGRE_DATABASE = 'POSTGRE_DATABASE',

  ACCESS_SECRET_KEY = 'ACCESS_SECRET_KEY',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  DIRECTORY_IMAGE = 'DIRECTORY_IMAGE',
  MAX_SIZE_IMAGE = 'MAX_SIZE_IMAGE',
  EXTENSION_AVAILABLE_IMAGE = 'EXTENSION_AVAILABLE_IMAGE',
}
